import { env } from "./env";

/**
 * Names of the auth cookies set on the web origin. The `__Host-` prefix
 * restricts the cookies to Secure, Path=/ and no Domain attribute, which
 * prevents subdomain and http cookie injection.
 */
export const COOKIES = {
  access: "__Host-mp_access",
  refresh: "__Host-mp_refresh",
} as const;

/** Access-token lifetime. Access tokens are short-lived; they are refreshed
 *  through the opaque rotating refresh token. */
export const ACCESS_TOKEN_TTL_S = 15 * 60; // 15 minutes
export const ACCESS_TOKEN_TTL_JOSE = "15m";

/** Session lifetime when "remember me" is not selected. */
export const SESSION_DEFAULT_TTL_MS = 12 * 60 * 60 * 1000; // 12 hours

/** Session lifetime when "remember me" is selected. */
export const SESSION_REMEMBER_TTL_MS = env.refreshTtlDays * 24 * 60 * 60 * 1000;

export const TOKEN_KINDS = {
  EMAIL_VERIFY: "EMAIL_VERIFY",
  PASSWORD_RESET: "PASSWORD_RESET",
} as const;

export const EMAIL_VERIFY_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours
export const PASSWORD_RESET_TTL_MS = 4 * 60 * 60 * 1000; // 4 hours

export const AUDIT_ACTIONS = {
  REGISTER: "AUTH_REGISTER",
  LOGIN: "AUTH_LOGIN",
  LOGOUT: "AUTH_LOGOUT",
  LOGOUT_ALL: "AUTH_LOGOUT_ALL",
  REFRESH: "AUTH_REFRESH",
  SESSION_REVOKED: "AUTH_SESSION_REVOKED",
  DEVICE_REVOKED: "AUTH_DEVICE_REVOKED",
  EMAIL_VERIFIED: "AUTH_EMAIL_VERIFIED",
  RESEND_VERIFICATION: "AUTH_RESEND_VERIFICATION",
  PASSWORD_RESET: "AUTH_PASSWORD_RESET",
  INVITE_CREATED: "ADMIN_INVITE_CREATED",
  INVITE_REVOKED: "ADMIN_INVITE_REVOKED",
  INVITE_USED: "AUTH_INVITE_USED",
  DATA_EXPORTED: "PRIVACY_DATA_EXPORTED",
  ACCOUNT_DELETED: "PRIVACY_ACCOUNT_DELETED",
  ACCOUNT_CREATED: "FINANCE_ACCOUNT_CREATED",
  ACCOUNT_UPDATED: "FINANCE_ACCOUNT_UPDATED",
  ACCOUNT_ARCHIVED: "FINANCE_ACCOUNT_ARCHIVED",
  CATEGORY_CREATED: "FINANCE_CATEGORY_CREATED",
  CATEGORY_UPDATED: "FINANCE_CATEGORY_UPDATED",
  CATEGORY_ARCHIVED: "FINANCE_CATEGORY_ARCHIVED",
  TRANSACTION_CREATED: "FINANCE_TRANSACTION_CREATED",
  TRANSACTION_UPDATED: "FINANCE_TRANSACTION_UPDATED",
  TRANSACTION_DELETED: "FINANCE_TRANSACTION_DELETED",
  TRANSFER_CREATED: "FINANCE_TRANSFER_CREATED",
  TRANSFER_UPDATED: "FINANCE_TRANSFER_UPDATED",
  TRANSFER_DELETED: "FINANCE_TRANSFER_DELETED",
  BUDGET_CREATED: "FINANCE_BUDGET_CREATED",
  BUDGET_UPDATED: "FINANCE_BUDGET_UPDATED",
  BUDGET_ARCHIVED: "FINANCE_BUDGET_ARCHIVED",
  DEBT_CREATED: "FINANCE_DEBT_CREATED",
  DEBT_UPDATED: "FINANCE_DEBT_UPDATED",
  DEBT_ARCHIVED: "FINANCE_DEBT_ARCHIVED",
  BILL_CREATED: "FINANCE_BILL_CREATED",
  BILL_UPDATED: "FINANCE_BILL_UPDATED",
  BILL_ARCHIVED: "FINANCE_BILL_ARCHIVED",
  BILL_PAID: "FINANCE_BILL_PAID",
} as const;

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  DISABLED: "DISABLED",
} as const;

export const USER_ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

export const INVITE_STATUS = {
  PENDING: "PENDING",
  USED: "USED",
  REVOKED: "REVOKED",
} as const;

/** Lifetime of a registration invitation link. */
export const INVITE_TTL_MS = 30 * 24 * 60 * 60 * 1000; // 30 days